name: Workflow1

on:
  pull_request:
    branches:
      - main  # change this to your main branch

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    outputs:
      # Define the output variable 'branch-name' with the value of the current branch
      # This can be accessed in other workflows using ${{ needs.workflow1.outputs.branch-name }}
      # 'value' is the default output name that will be used if not specified in the outputs section
      outputs: 'branch-name'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # change this to your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # change this if you have dependencies

    - name: Install jitterbit
      uses: jitterbit/get-changed-files@v1
      with:
        format: 'space-delimited'

    - id: files
      uses: jitterbit/get-changed-files@v1
    - run: |
        for changed_file in ${{ steps.files.outputs.all }}; do
          python validate_schema_json.py ${changed_file}
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.PAT }}
        event-type: my-event
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "test": "test message"}'
    
#  notify:
#    needs: run_python_script
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v2
#
#      - name: Set up Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.8  # change this to your desired Python version
#
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt  # change this if you have dependencies
#
#      - name: Install jitterbit
#        uses: jitterbit/get-changed-files@v1
#        with:
#          format: 'space-delimited'
#
#      - id: files
#        uses: jitterbit/get-changed-files@v1
#      - run: |
#          for changed_file in ${{ steps.files.outputs.all }}; do
#            python create_ttl_files.py ${changed_file}
#          done
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
