name: Run Python Script on Pull Request

on:
  pull_request:
    branches:
      - main  # change this to your main branch

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # change this to your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # change this if you have dependencies

    - name: Run Python script
      run: python validate_schema_json.py  # change this to the path of your Python script
