name: Second Workflow

on:
  workflow_run:
    workflows: ["run_python_script"]
    types:
      - completed

jobs:
  second_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # change this to your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # change this if you have dependencies

      - name: Install jitterbit
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'space-delimited'

      - id: files_2
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            python create_ttl_files.py ${changed_file}
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
