name: WorkflowOnMerge

on:
  pull_request:
    types:
      - closed

jobs:
  process-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history

    - name: Fetch all commit history
      run: git fetch --prune

    - name: Run your workflow only on changed files
      run: |
        # Get the list of changed files in the pull request
        changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

        # Run your workflow commands only on changed files
        echo "Changed files: $changed_files"

        # Add your workflow steps here that need to be executed on changed files
        for changed_file in ${changed_files}; do
          python create_ttl_files.py ${changed_file}
        done
        
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
