name: Workflow 2

on:
  workflow_run:
    workflows: [Workflow1]
    types:
      - completed

jobs:
  process-changes:
    runs-on: ubuntu-latest

    steps:

    - name: Print branch name
      run: echo "${{ github.event.inputs.branch_name }}"

    - name: Print Branch Name from Workflow1
      run: |
        echo "Branch Name from Workflow1: ${{fromJson(needs.Workflow1.outputs.outputs).branch-name}}"
        echo "${{(needs)}}"
        echo "${{fromJson(needs)}}"
        echo "${{fromJson(needs.Workflow1)}}"
        echo "${{fromJson(needs.Workflow1).branch-name}}"
        echo "${{fromJson(needs.Workflow1.outputs.outputs).branch-name}}"

    - name: Print branch name
      run: echo "${{ env.BRANCH_NAME }}"
        
    - name: Check out the code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history

    - name: Fetch all commit history
      run: git fetch --prune

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # change this to your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # change this if you have dependencies

    - name: Run your workflow only on changed files
      run: |
        # Get the list of changed files in the pull request
        changed_files=$(git diff --name-only HEAD^ HEAD)

        # Run your workflow commands only on changed files
        echo "Changed files: $changed_files"

        # Add your workflow steps here that need to be executed on changed files
        for changed_file in ${changed_files}; do
          python create_ttl_files.py ${changed_file}
        done
        
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
