name: Second Workflow

on:
  workflow_run:
    workflows: [Run Tests]
    types:
      - completed

jobs:
  second_job:
    runs-on: ubuntu-latest

    steps:
    - name: Download Commit ID Artifact
      uses: actions/download-artifact@v2
      with:
        name: commit-id
        path: .

    - name: Use Commit ID
      run:
        echo "The commit ID is: $(cat commit-id)"
